apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding

metadata:

  name: triggers-eventlistener-binding

  namespace: diploe2-dvp

subjects:

- kind: ServiceAccount

  name: tekton-triggers-sa

  namespace: diploe2-dvp

roleRef:

  apiGroup: rbac.authorization.k8s.io

  kind: ClusterRole

  name: tekton-triggers-eventlistener-roles
