
apiVersion: serving.knative.dev/v1

kind: Service

metadata:

  name: especies-service

spec:

  template:

    spec:

      containers:

        - image: docker.io/davepo/proyecto-cloud:v1

          env:

            - name: MONGODB_CONNECTION_STRING

              valueFrom:

                secretKeyRef:

                  name: mongodb-atlas-secret

                  key: connection-string
