apiVersion: tekton.dev/v1beta1

kind: TaskRun

metadata:

  name: git-clone-run  # Nombre específico en lugar de generateName

  namespace: diploe2-dvp

spec:

  taskRef:

    kind: Task

    name: git-clone  # Referencia a la Task "git-clone"

  podTemplate:

    securityContext:

      fsGroup: 65532  # Permisos de escritura en el volumen

  params:

    - name: url

      value: https://github.com/yodavepo/especies  # URL del repositorio a clonar

    - name: deleteExisting

      value: "true"  # Elimina el contenido existente antes de clonar
   
    - name: revision
      
      value: main

  workspaces:

    - name: output

      persistentVolumeClaim:  # Usa un volumen persistente en lugar de emptyDir

        claimName: workspace  # Nombre del PersistentVolumeClaim (PVC)
