apiVersion: tekton.dev/v1beta1

kind: TaskRun

metadata:

  generateName: buildah-run

  namespace: diploe2-dvp # Reemplaza con tu namespace

spec:

  taskRef:

    name: buildah

  params:

    - name: IMAGE

      value: 'docker.io/davepo/especies/v1' # Reemplaza con tu imagen

      # ej. value: 'docker.io/cafaray/notificaciones:V2.2'

    - name: TLSVERIFY

      value: 'false'

    - name: STORAGE_DRIVER

      value: 'vfs'

  workspaces:

    - name: source

      persistentVolumeClaim:

        claimName: workspace

    - name: dockerconfig

      secret:

        secretName: dockerconfig-secret
