apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding

metadata:

  name: tekton-role # Nombre descriptivo

  namespace: diploe2-dvp

subjects:

- kind: ServiceAccount

  name: tekton-sa

  namespace: diploe2-dvp # Asegúrate de que este namespace coincida

roleRef:

  kind: Role # O ClusterRole si usas un ClusterRole

  name: deployment-editor # El nombre del Role que creaste

  apiGroup: rbac.authorization.k8s.io
