apiVersion: tekton.dev/v1beta1

kind: PipelineRun

metadata:

  generateName: pipelinerun-clone-package-

  namespace: diploe2-dvp

spec:

  serviceAccountName: tekton-sa

  pipelineRef:

    name: pipeline-clone-package

  params:

    - name: repo-url

      value: https://github.com/yodavepo/especie.git

    - name: maven-image

      value: gcr.io/cloud-builders/mvn@sha256:8f38a2667125a8d83f6e1997847fedb6a06f041c90e2244884153d85d95f869b

  workspaces:

    - name: maven-settings

      configmap:

        name: maven-settings

    - name: workspace

      persistentVolumeClaim:

        claimName: workspace
