apiVersion: tekton.dev/v1beta1

kind: PipelineRun

metadata:

  generateName: pipelinerun-helloworld-
  namespace: diploe2-dvp  # Asegúrate de que el namespace esté correctamente especificado

spec:

  serviceAccountName: tekton-sa

  pipelineRef:

    name: pipeline-hello-world

  params:

    - name: your-name

      value: "David"

    - name: repo-url

      value: https://github.com/yodavepo/especies.git

  workspaces:

    - name: empty-dir

      emptyDir: {}
